package com.plamera.tmswiftlauncher;

import java.util.ArrayList;
import java.util.Date;

public class Global {
    public static String UrlLogin;
    public static boolean connected3G = false;
    public static boolean connectedToWiFi = false;
    public static String ServerStatus = "";
    public static String ServerDate = "";
    public static String URLSwift = "";
    public static String currentAPN = "";
    public static Object loginContext;
    public static String localIP;
    public static boolean MaxisRouter = false;
    public static boolean CanPing = false;
    public static String reqUsingServerDate = "";
    public static String updateUsingServerDateTime = "" ;
    public static String TTreqSummDate;
    public static String FFreqSummDate;
    public static int AssignInprogressCount;
    public static int OutstandingMA;
    public static boolean LogAsAdmin;
    public static boolean PhoneValid;
    public static boolean releaseVersion;
    public static String usernameBB = "";
    public static String loginServer;
    public static String loginServerLevel;
    public static DatabaseHandler mySQLiteAdapter;
    public static long manualID;
    public static String URLAuthenticate;
    public static Date lastAlertTime;
    public static boolean detailsStillEmpty;
    public static String TTApointList;
    public static int FFAssignCount;
    public static int allTaskCounter;
    public static int countCF;
    public static boolean FirstTimeRunLogin;
    public static boolean CreateMainMenu;
    public static String strVersion;
    public static String frmVersion;
    public static String NumberOFUnauthorize;
    public static String IMEIPhone;
    public static String IMSIsimCardPhone;
    public static String staffName;
    public static boolean blnUpdateMatNum;
    public static boolean blnUpdateLOV;
    public static String staffIcNo = "";
    public static String AppVersion;
    public static String AppCode;
    public static String AppVersionLink;
    public static String AppSize;
    public static String UserType;
    public static boolean MustPassLockScreen;
    public static boolean LoginMonitor;
    public static String NewVersionFileName;
    public static ArrayList<String> blacklistedNumbers;
    public static long downloadID;
    public static boolean updateReady;
    public static boolean waitingForDownload;
    public static boolean upgradeInProgress;
    public static String passwordBB;
    public static String EmmStatus = "";
    public static String getToken = "";
    public static String netType = "";
    public static String latitude = "";
    public static String longitude = "";
    public static String availMemory = "";
    public static int getLac = 0;
    public static int getCid = 0;
    public static String batState = "";
    public static String getLoginStatus = "";
    public static String status = "Offline";
    public static int batLvl = 0;
    public static String launcherVer = "";
    public static String agentVer = "";
    public static String ldapStatus = "";
    public static String getMessage = "";
    public static String getTask = "";
    public static String getQueue = "";
    public static String responseResult = "";
    public static Boolean loginResult;
    public static String myStatus = "";
    public static String swiftVer = "";
}
